name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: gyan007
          outputs: dist/snake.svg

      # Ensure output folder exists
      - name: Prepare output folder
        run: mkdir -p dist

      # Move the generated SVG to the output folder
      - name: Move SVG
        run: mv snake.svg dist/snake.svg

      # Deploy to the main branch
      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
